# Generated by Django 5.2.1 on 2025-05-29 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='部門タイトル')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名前')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('salary', models.IntegerField(verbose_name='給料')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.department', verbose_name='関連部門')),
            ],
        ),
    ]
