# Generated by Django 5.2.1 on 2025-06-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性別'),
        ),
    ]
