# Generated by Django 5.2 on 2025-04-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='123456', max_length=64, verbose_name='パスワード'),
        ),
    ]
