# Generated by Django 5.2.1 on 2025-06-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='ユーザー名')),
                ('password', models.CharField(max_length=64, verbose_name='パスワード')),
                ('age', models.IntegerField(verbose_name='年齢')),
            ],
        ),
    ]
